import Link from 'next/link';

export default function TermsOfService() {
  return (
    <main className="min-h-screen bg-[#f6f5ef] text-black overflow-x-hidden w-full font-sans">
      
      {/* Header */}
      <header className="w-full flex items-center px-4 sm:px-8 py-3 sm:py-4 bg-white border-b border-gray-200 sticky top-0 z-50">
        <Link href="/" className="max-w-5xl mx-auto w-full flex items-center hover:opacity-70 transition-opacity">
          <span className="text-xl sm:text-2xl mr-2">🌍</span>
          <span className="font-marker font-bold text-xl sm:text-2xl mr-2 text-black">HowToDo</span>
          <span className="font-sans font-bold text-[9px] sm:text-[10px] tracking-[0.25em] uppercase opacity-40" style={{ WebkitTextStroke: '1px #666', color: 'transparent' }}>WORLD</span>
        </Link>
      </header>

      {/* Content */}
      <div className="w-full max-w-3xl mx-auto px-6 py-16 sm:py-24">
        <h1 className="font-marker font-bold text-5xl sm:text-6xl mb-8 text-black tracking-tight">Terms of Service</h1>
        
        <div className="space-y-10 font-serif text-gray-600 leading-relaxed text-lg sm:text-xl">
          <p className="text-sm font-sans tracking-widest uppercase text-gray-400 font-bold">Effective Date: Today</p>
          
          <section>
            <h2 className="font-marker text-3xl text-black mb-4">1. Acceptance of Terms</h2>
            <p>By accessing and using HowToDo World, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by these terms, please do not use this service.</p>
          </section>

          <section>
            <h2 className="font-marker text-3xl text-black mb-4">2. AI-Generated Content Disclaimer</h2>
            <p>The roadmaps, checklists, and guides provided on this platform are generated by Artificial Intelligence. While we strive for accuracy, this content is for educational and informational purposes only. It should not be considered professional legal, medical, or financial advice. Always verify important information independently.</p>
          </section>

          <section>
            <h2 className="font-marker text-3xl text-black mb-4">3. User Conduct</h2>
            <p>You agree to use the platform only for lawful purposes. You are prohibited from using the site to generate harmful, illegal, or malicious instructions. We reserve the right to block queries that violate safety guidelines.</p>
          </section>

          <section>
            <h2 className="font-marker text-3xl text-black mb-4">4. Limitation of Liability</h2>
            <p>HowToDo World and its creators shall not be held liable for any direct, indirect, incidental, or consequential damages resulting from the use or inability to use the roadmaps provided by our AI systems.</p>
          </section>
        </div>

        <div className="mt-20">
          <Link href="/" className="inline-block px-10 py-5 border-[3px] border-black text-black font-marker text-sm uppercase tracking-widest hover:bg-black hover:text-white transition-colors shadow-[6px_6px_0px_0px_rgba(0,0,0,1)] active:shadow-none active:translate-y-1">
            ← Back to Home
          </Link>
        </div>
      </div>
    </main>
  );
}
